// Code generated by Slice Machine. DO NOT EDIT.

import BracketSlice from './BracketSlice';
import CountdownSlice from './CountdownSlice';
import DuelsSlice from './DuelsSlice';
import EmailSignupSlice from './EmailSignupSlice';
import EventListSlice from './EventListSlice';
import EventScheduleSlice from './EventScheduleSlice';
import FaqSlice from './FaqSlice';
import FeedEmbedSlice from './FeedEmbedSlice';
import HeroVideoSlice from './HeroVideoSlice';
import ImageBannerSlice from './ImageBannerSlice';
import ImageCarouselSlice from './ImageCarouselSlice';
import ImageContentHeroSlice from './ImageContentHeroSlice';
import ImageSliderSlice from './ImageSliderSlice';
import PartnerLogoGridSlice from './PartnerLogoGridSlice';
import RiderGallerySlice from './RiderGallerySlice';
import RiderRandomizerSlice from './RiderRandomizerSlice';
import Streams from './Streams';
import TextSlice from './TextSlice';
import TwoColumnSlice from './TwoColumnSlice';
import WebglModelSlice from './WebglModelSlice';

export {
	BracketSlice,
	CountdownSlice,
	DuelsSlice,
	EmailSignupSlice,
	EventListSlice,
	EventScheduleSlice,
	FaqSlice,
	FeedEmbedSlice,
	HeroVideoSlice,
	ImageBannerSlice,
	ImageCarouselSlice,
	ImageContentHeroSlice,
	ImageSliderSlice,
	PartnerLogoGridSlice,
	RiderGallerySlice,
	RiderRandomizerSlice,
	Streams,
	TextSlice,
	TwoColumnSlice,
	WebglModelSlice,
};

export const components = {
	bracket_slice: BracketSlice,
	countdown_slice: CountdownSlice,
	duels_slice: DuelsSlice,
	email_signup_slice: EmailSignupSlice,
	event_list_slice: EventListSlice,
	event_schedule_slice: EventScheduleSlice,
	faq_slice: FaqSlice,
	feed_embed_slice: FeedEmbedSlice,
	hero_video_slice: HeroVideoSlice,
	image_banner_slice: ImageBannerSlice,
	image_carousel_slice: ImageCarouselSlice,
	image_content_hero_slice: ImageContentHeroSlice,
	image_slider_slice: ImageSliderSlice,
	partner_logo_grid_slice: PartnerLogoGridSlice,
	rider_gallery_slice: RiderGallerySlice,
	rider_randomizer_slice: RiderRandomizerSlice,
	streams: Streams,
	text_slice: TextSlice,
	two_column_slice: TwoColumnSlice,
	webgl_model_slice: WebglModelSlice,
};
