export const LENGTH = 40

export const RIDERS = [
  { name: 'anna gasser', fileName: 'anna_gasser.jpg' },
  { name: 'austen sweetin', fileName: 'austen_sweetin.jpg' },
  { name: 'ben ferguson', fileName: 'ben_ferguson.jpg' },
  { name: 'blake paul', fileName: 'blake_paul.jpg' },
  { name: 'bode merrill', fileName: 'bode_merrill.jpg' },
  { name: 'chris rasman', fileName: 'chris_rasman.jpg' },
  { name: 'elena hight', fileName: 'elena_hight.jpg' },
  { name: 'elhardt elias', fileName: 'elhardt_elias.jpg' },
  { name: 'eric jackson', fileName: 'eric_jackson.jpg' },
  { name: 'gigi ruf', fileName: 'gigi_ruf.jpg' },
  { name: 'hailey langlands', fileName: 'hailey_langlands.jpg' },
  { name: 'hana beaman', fileName: 'hana_beaman.jpg' },
  { name: 'jamie anderson', fileName: 'jamie_anderson.jpg' },
  { name: 'marion haerty', fileName: 'marion_haerty.jpg' },
  { name: 'mark mcmorris', fileName: 'mark_mcmorris.jpg' },
  { name: 'mikkel bang', fileName: 'mikkel_bang.jpg' },
  { name: 'nils mindnich', fileName: 'nils_mindnich.jpg' },
  { name: 'pat moore', fileName: 'pat_moore.jpg' },
  { name: 'robin vangyn', fileName: 'robin_vangyn.jpg' },
  { name: 'sage kotsenburg', fileName: 'sage_kotsenburg.jpg' },
  { name: 'travis rice', fileName: 'travis_rice.jpg' },
  { name: 'verni stock', fileName: 'verni_stock.jpg' },
  { name: 'victor delerue', fileName: 'victor_delerue.jpg' },
  { name: 'zoi sadowski-synnott', fileName: 'zoi_sadowski-synnott.jpg' },
]
